### PR TITLE
Fix forward secrecy

### PR DESCRIPTION
**Pull request by urost**
Merge the fix for preferring the use of good ciphers for forward secrecy.

### CODE REVIEW

**Review by marcvs — APPROVED** [review]
Fixes ssllabs from B to A

**Comment by orviz** [comment]
add to whitelist

**Comment by orviz** [comment]
add to whitelist

**Comment by orviz** [comment]
add to whitelist

**Comment by orviz** [comment]
test this please

**Comment by orviz** [comment]
retest this please

**Pull request merged**
